whatwg/console

index.bs, package.json
Still some remaining issues: https://github.com/bterlson/ecmarkup/issues/77 and https://github.com/bterlson/ecmarkup/issues/76 but they are not our fault.
=> Fix #24: abstract operations should now be autolinked

index.bs
The specification says that  Logger should not perform anything
if data is empty. However, console.assert() should not be required
to provide an argument besides the condition to log something,
which matches what most implementations do.
This clarifies that section in the spec by providing an algorithm
as well as a recommendation of prefixing messages without destroying
formatting capabilities.
=> console.assert should always call logger with non-empty data (fixes #85)

index.bs
As mentioned in #86 so that the next person copy-pasting doesn't run into this.
Seems to be more consistent with other WHATWG specs, like https://html.spec.whatwg.org/
> [...] A U+0054 LATIN CAPITAL LETTER T character (T) or a U+0020 SPACE character [...]
> [...] of the string "CACHE", a single U+0020 SPACE character, the string "MANIFEST" [...]
=> Remove unorthodox parens around symbol name SPACE

NOTES.md
Just formatting some of the content in notes, and adding the differences found with `time() / timeEnd()` and associated bugs. Will close https://github.com/whatwg/console/issues/26 when this is merged.
With changes like [this](https://github.com/whatwg/console/compare/update-notes?expand=1#diff-c7375ff11bc41bd2c1fbde6f98f5904aL11) I'm not sure if the comma was intentional or not, so I changed to a decimal (what I see as the output)
=> Format NOTES, add time() differences

index.bs
Since I put some group-specific logic inside `Printer` (see "When a group gets printed, output produced by future calls...") should we have a new log level "group" for this to be a little more detectable and rigorous? This would be used inside `group()` and `groupCollapsed()`.
I think the language describing a `group` is both helpful and vague enough to allow browsers to implement this one way, and Node another (possibly even with prefixes since previously outputted data typically is non-interactive) while still being compliant. Thoughts?
Addresses https://github.com/whatwg/console/issues/94
=> Language for grouping methods

index.bs
This adds language for `dir` and `dirxml` to the spec.
Whenever we call `Printer` in the spec it seems that we've already made the necessary transformations or conversions ourselves to the objects we're about to pass into `Printer`. To avoid duplication, `group` was defined outside of the methods that use it, therefore anything needing to print a group just says new `group` instead of new `view to host the output produced......`.
In `dirxml` I reused the `%o` format specifier description, and in `dir` I reused portions of the `%O` format specifier description; so I'm wondering if we should define things like:
- `Generic JavaScript object representation`
and
- `Optimally useful representation` (or similarly named)
somewhere near Printer so in the future we could say things like
- "Let …
=> Add dir + dirxml to IDL and spec

index.bs
First go at factoring out definitions we've duplicated in the spec when referring to the Printing of objects. Will close #97.
Originally I was going to put the dfns in the main Printer section but decided that just mashing them in between paras might not be the best way to keep that section clean.
=> Factor out object formatting definitions

.editorconfig, .gitattributes
Part of https://github.com/whatwg/meta/issues/7.
I *believe* this will also instruct GitHub to wrap lines in .bs files by treating them as .html files. That should help reviewing a lot.
Alternately the spec could start wrapping at 100 characters like most WHATWG specs; not sure if that's worthwhile/what the editors want though.
=> Meta: add .editorconfig and .gitattributes

.editorconfig, index.bs
This PR
- Adds `max_line_length = 100` to the `.editorconfig`
- Adds newlines where editor line-breaks happen regularly so we can get rid of the dots we see in the following pic:
The newlines have been added everywhere except for in the middle of long inline elements (like `<h3 many attributes here....>`) and the header metadata (got BS errors when adding newlines in between `<a>`s here).
The diff can show that no text is modified and only newlines are added.
=> Add max_line_length

index.bs
Notable changes include the addition of a colon to the output, being explicit about how the implementation decides the format of the duration string, and making the timer table concept explicit.
This also fixes up a few minor linking errors, e.g. two elements having the same ID "group".
=> Make the spec for time()/timeEnd() a bit more accurate and rigorous

index.bs
Will close: https://github.com/whatwg/console/issues/79.
I am not sure if the `h3` Printer header will need any special symbols on the `options` object to indicate that it is optional and thus make all other calls to Printer with two arguments valid.
This also addresses a small typo I missed when adding text about the group stack in Printer.
=> Support Nodejs dir

index.bs
Addresses https://github.com/whatwg/console/issues/114
Attempt to define `console.count()` label behavior by using an ordered map entry for each label:  https://infra.spec.whatwg.org/#maps
Specifies that a map object should be created, and that calls to count with that label should increment the value associated with the label.  If a label is undefined, a label passed to count will set the value of key _label_ to be 1.
=> [#114] Specify map for console.count labels

README.md
I didn't remove the `node_modules/` and `npm-debug.log` entries in `.gitignore`, because they might appear in `reference-implementation/` or `test/`.
=> Editorial: do not mention emu-algify in README.md

index.bs
First attempt at #113. I see two ways to go about this:
- [Initial attempt] Use `String()` instead `ToString()` when Formatter converts arguments with the `%s` specifier. Behavior is the same as `ToString()` except it doesn't throw when converting Symbols. Not sure if this is a viable since `String()` isn't an abstract internal-only operating (are we limited to using these at all? Is it bag to call a constructor in this kinda position?)
- Run a `Type()` check before we convert with `ToString()`, and call [`SymbolDescriptiveString`](https://tc39.github.io/ecma262/#sec-symboldescriptivestring) in the case we have a Symbol. (Basically performing the logic of the `String()` constructor ourselves).
Both of the above ways will prevent Formatter from throwing so the changes aren't big, and are …
=> Fix Formatter to use String() instead of ToString()

CONTRIBUTING.md, README.md
This:
- Adds CONTRIBUTING.md (which directly references whatwg/meta's CONTRIBUTING.md and indirectly references whatwg/meta's COMMITTING.md)
- Rearrange some stuff in README.md and reference the local CONTRIBUTING.md
- Add `Merge policy` section to the README.md
Closes #125
=> Meta: Add whatwg/meta references

index.bs
This fixes #126. I went with `Call(%String%...)` even though %String% does have the `[[Construct]]` internal method, because I saw no benefit to using `Construct(%String%...)` here as the `newTarget` is irrelevant.
I prefer the bikeshed shorthand `[$Call$](...)` however I notice we don't always seem to use it in this spec. If anyone wants me to either revert this instance of the shorthand, or update all other links to use the shorthand (for the sake of consistency) I'm happy to do either.
Finally, I've used a bold **undefined** to denote `undefined` in ES, as it is passed into the `Call` abstract operation as the `this` value. Not sure if this is the *right* move, but I drew inspiration from the Streams Standard.
=> Use `Call` to call %parseInt/Float% and %String%

index.bs
Closes #113 and ensures that the Formatter will not throw an error when applying `%{i, d, f}` format specifiers when applied to Symbols. https://github.com/w3c/web-platform-tests/pull/9488 will need updated but I can get to that soon.
=> Ensure number format specifiers don't throw on Symbols

index.bs
We've discussed adding a method `countReset` to `console` in #89. We've got two major implementations that have it, so it seems worth speccing, however the two behave differently. There are two things it seems we have to specify: How calls to the API should behave with a label that has:
- **An associated count** - `console.countReset("labelWithCount")`
- In Edge, I believe "labelWithCount: 0" is produced
- In Node, no output is produced.
- **No associated count** - `console.countReset("labelWithNoCount")`
- In Edge,  "null: 0" is produced the first time, and nothing is produced subsequent times
- In Node, no output is produced when we reset the count that doesn't exist.
Here are the proposals I have in this PR:
- **An associated count**
- I personally that no output should be produced …
=> Specify console.countReset

index.bs
Hello, I could find some time to work on this, though I am not experienced with Bikeshed.
There is another `%String%` reference in the spec, generated using the `{{%String%}}` syntax; however it appears as an orangered link, not a blue one like for the `%parseInt%` and `%parseFloat%` functions.
Is this behavior intended so I should have used the same syntax, or is there something to do about both references?
=> Fix leftover ToString reference in format specifier table's %s entry

index.bs
This PR:
- Adds `timeLog` to the Console Standard (and specifies that it should use `Printer` instead of `Logger` so we ignore format specifiers appearing in a timer label.
- Cleans up the way we interact with associated `timer table`s in the timing methods - this is a little prep work for later when we check (non)existence of `timer table` entries so we can formally report warnings.
- Points to an issue #134 to show plans for having the timing methods formally report warnings.
- Fixes `timeEnd` to actually remove a timer from the timer table (the reason we went with adding `timeLog`)
- Adds an example show how someone might use the extra `...data` passed into `timeLog` to distinguish calls to `timeLog` from each other throughout the duration of a timer.
- Fixes `countReset`'s permalink …
=> Specify console.timeLog() + clean up timing

index.bs
To match the style of other permalinks. There are a few links to the camelCase version of think link in WPTs which I'll update separately.
=> Editorial: fix countReset permalink

index.bs
Closes #57. Not entirely familiar with creating an exportable definition in Bikeshed, but given some examples in whatwg/dom and friends I take it the `export` keyword is sufficient for Bikeshed to pick it up?
Also I'm happy to make a `ReportWarning(...)` abstract operation instead of just a dfn that can be given "a generic warning", but I figured I'd go down this route first.
Edit: #57 mentions it might be good to make this _optionally call Printer(...)_, but personally I prefer to make it mandatory, and have callers _optionally_ call into our definition. I think this will make their specs more clear.
=> Report warning

index.bs
WebKit, Chromium, and Gecko all support calling `console.dir` and `console.table` with no first argument (e.g. no exception is thrown), so the spec should match these implementations.  Given that every other `console` method allows for any number of arguments without throwing an error, it's reasonable to have `console.dir` and `console.table` do the same.
The implications of this is that `console.dir.length` and `console.table.length` would now be equal to `0`. 
```diff
[Exposed=(Window,Worker,Worklet)]
namespace console { // but see namespace object requirements below
// Logging
void assert(optional boolean condition = false, any... data);
void clear();
void debug(any... data);
void error(any... data);
void info(any... data);
void log(any... data);
-  void table(any tabularData, optional …
```
=> Make first argument of `console.dir` and `console.table` optional (#159)

index.bs
This should fix the build, and unblock the remaining PRs. The width/height attributes that I assigned to the `<img>` elements in the spec are just the exact width/heights of the actual images.
***
<a href="https://whatpr.org/console/212.html" title="Last updated on May 17, 2022, 5:53 PM UTC (1883714)">Preview</a> | <a href="https://whatpr.org/console/212/6447e9d...1883714.html" title="Last updated on May 17, 2022, 5:53 PM UTC (1883714)">Diff</a>
=> Assign width/height attributes to images

index.bs
Ref: https://github.com/tc39/proposal-shadowrealm/issues/331
* Positive initial signals from Google, Apple, Mozilla on the general direction.
* https://github.com/web-platform-tests/wpt/pull/34361
* Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1281880
* Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1747059
* Safari: https://bugs.webkit.org/show_bug.cgi?id=234554
(See [WHATWG Working Mode: Changes](https://whatwg.org/working-mode#changes) for more details.)
***
<a href="https://whatpr.org/console/209.html" title="Last updated on Jun 14, 2022, 8:13 AM UTC (334b6f3)">Preview</a> | <a href="https://whatpr.org/console/209/21f55a4...334b6f3.html" title="Last updated on Jun 14, 2022, 8:13 AM UTC (334b6f3)">Diff</a>
=> Expose everywhere

index.bs
Hi! This is my first contribution to a spec like this so while I've done my best to follow the guidelines, there are probably things I am getting wrong. Let me know and I'll try and sort them out as soon as possible.
---
This fixes #204.
As noted in that issue, several functions call `Formatter` without
checking that a format specifier is present, but the `Formatter`
algorithm assumed this was never the case. When called in this way,
`Formatter` would use the `result` variable without defining it.
This patch makes the following changes:
- Add a step 4 to the `Formatter` algorithm to explicitly handle a lack
of format specifier.
- Correct the indentation of what was step 3.8 of `Formatter`, so it is
now step 6.
- Remove what was step 4 from `Formatter`, since this is now redundant.
- …
=> Handle input with no format specifiers in `Formatter`

NOTES.md
This PR makes some progress on #181 by removing the "Float parsing" section of NOTES.md. Firefox and _sometimes_ Safari deviate from the spec in a couple of ways, so I've filed bugs with their implementation to track the difference:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1846606
- https://bugs.webkit.org/show_bug.cgi?id=259703
=> Remove float parsing section of NOTES.md

index.bs
Inspired by #239 which mysteriously closed.
***
<a href="https://whatpr.org/console/240.html" title="Last updated on Sep 23, 2024, 5:14 PM UTC (5ab537f)">Preview</a> | <a href="https://whatpr.org/console/240/7a9c402...5ab537f.html" title="Last updated on Sep 23, 2024, 5:14 PM UTC (5ab537f)">Diff</a>
=> Editorial: Use implementation-defined more
